In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# track.csv contains the origination information for each track(artist, album year of release, genre catagories,etc)
# genres.csv is a genre-look up table,
# features.csv and echonest.csv are two sets of extracted audio features generated through the Librosa,
# and Echonest libraries, with each song labeled by it's track id.

In [ ]:
tracks = pd.read_csv('tracks.csv')
genres = pd.read_csv('genres.csv')
features = pd.read_csv('features.csv')
echonest = pd.read_csv('echonest.csv')

FileNotFoundError: File b'tracks.csv' does not exist

In [1]:
#tracks
tracks.columns

NameError: name 'tracks' is not defined

In [5]:

tracks.head()

,Unnamed: 0,album,album.1,album.2,album.3,album.4,album.5,album.6,album.7,album.8,...,track.10,track.11,track.12,track.13,track.14,track.15,track.16,track.17,track.18,track.19
0,NaN,comments,date_created,date_released,engineer,favorites,id,information,listens,producer,...,information,interest,language_code,license,listens,lyricist,number,publisher,tags,title
1,track_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,...,NaN,4656,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1293,NaN,3,NaN,[],Food
3,3,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,...,NaN,1470,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,514,NaN,4,NaN,[],Electric Ave
4,5,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,...,NaN,1933,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1151,NaN,6,NaN,[],This World

In [21]:

tracks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106576 entries, 0 to 106575
Data columns (total 53 columns):
Unnamed: 0    106575 non-null object
album         106575 non-null object
album.1       103046 non-null object
album.2       70295 non-null object
album.3       15297 non-null object
album.4       106575 non-null object
album.5       106575 non-null object
album.6       83150 non-null object
album.7       106575 non-null object
album.8       18061 non-null object
album.9       106575 non-null object
album.10      105550 non-null object
album.11      106575 non-null object
album.12      100067 non-null object
artist        22712 non-null object
artist.1      5376 non-null object
artist.2      14272 non-null object
artist.3      71157 non-null object
artist.4      106575 non-null object
artist.5      105719 non-null object
artist.6      106575 non-null object
artist.7      106575 non-null object
artist.8      44545 non-null object
artist.9      70211 non-null object
artist.10     44545 non-null object
artist.11     46850 non-null object
artist.12     106575 non-null object
artist.13     13153 non-null object
artist.14     106575 non-null object
artist.15     79262 non-null object
artist.16     5582 non-null object
set           106575 non-null object
set.1         106575 non-null object
track         106575 non-null object
track.1       106575 non-null object
track.2       3836 non-null object
track.3       106575 non-null object
track.4       6160 non-null object
track.5       106575 non-null object
track.6       106575 non-null object
track.7       49599 non-null object
track.8       106575 non-null object
track.9       106575 non-null object
track.10      2510 non-null object
track.11      106575 non-null object
track.12      15025 non-null object
track.13      106488 non-null object
track.14      106575 non-null object
track.15      482 non-null object
track.16      106575 non-null object
track.17      1435 non-null object
track.18      106575 non-null object
track.19      106574 non-null object
dtypes: object(53)
memory usage: 43.1+ MB

In [1]:
tracks.describe(include='all')

NameError: name 'tracks' is not defined

In [2]:
#genres
genres.columns

NameError: name 'genres' is not defined

In [8]:
genres.head()

   genre_id  #tracks  parent          title  top_level
0         1     8693      38    Avant-Garde         38
1         2     5271       0  International          2
2         3     1752       0          Blues          3
3         4     4126       0           Jazz          4
4         5     4106       0      Classical          5

In [10]:
genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 5 columns):
genre_id     163 non-null int64
#tracks      163 non-null int64
parent       163 non-null int64
title        163 non-null object
top_level    163 non-null int64
dtypes: int64(4), object(1)
memory usage: 6.4+ KB

In [26]:
genres.isnull().sum()

genre_id     0
#tracks      0
parent       0
title        0
top_level    0
dtype: int64

In [22]:
genres.describe(include='all')

           genre_id       #tracks       parent      title    top_level
count    163.000000    163.000000   163.000000        163   163.000000
unique          NaN           NaN          NaN        163          NaN
top             NaN           NaN          NaN  Loud-Rock          NaN
freq            NaN           NaN          NaN          1          NaN
mean     254.116564   2142.085890    60.447853        NaN    51.374233
std      265.048642   5199.542574   185.396011        NaN   211.470836
min        1.000000      0.000000     0.000000        NaN     2.000000
25%       60.500000    125.000000     5.000000        NaN     5.000000
50%      172.000000    563.000000    15.000000        NaN    12.000000
75%      400.500000   1846.500000    38.000000        NaN    20.000000
max     1235.000000  38154.000000  1235.000000        NaN  1235.000000

In [11]:
#features
features.columns

Index(['feature', 'chroma_cens', 'chroma_cens.1', 'chroma_cens.2',
       'chroma_cens.3', 'chroma_cens.4', 'chroma_cens.5', 'chroma_cens.6',
       'chroma_cens.7', 'chroma_cens.8',
       ...
       'tonnetz.39', 'tonnetz.40', 'tonnetz.41', 'zcr', 'zcr.1', 'zcr.2',
       'zcr.3', 'zcr.4', 'zcr.5', 'zcr.6'],
      dtype='object', length=519)

In [25]:
features.head(8)

,feature,chroma_cens,chroma_cens.1,chroma_cens.2,chroma_cens.3,chroma_cens.4,chroma_cens.5,chroma_cens.6,chroma_cens.7,chroma_cens.8,...,tonnetz.39,tonnetz.40,tonnetz.41,zcr,zcr.1,zcr.2,zcr.3,zcr.4,zcr.5,zcr.6
0,statistics,kurtosis,kurtosis,kurtosis,kurtosis,kurtosis,kurtosis,kurtosis,kurtosis,kurtosis,...,std,std,std,kurtosis,max,mean,median,min,skew,std
1,number,01,02,03,04,05,06,07,08,09,...,04,05,06,01,01,01,01,01,01,01
2,track_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,7.1806526184e+00,5.2303090096e+00,2.4932080507e-01,1.3476201296e+00,1.4824777842e+00,5.3137123585e-01,1.4815930128e+00,2.6914546490e+00,8.6686819792e-01,...,5.4125156254e-02,1.2225749902e-02,1.2110591866e-02,5.7588901520e+00,4.5947265625e-01,8.5629448295e-02,7.1289062500e-02,0.0000000000e+00,2.0898721218e+00,6.1448108405e-02
4,3,1.8889633417e+00,7.6053929329e-01,3.4529656172e-01,2.2952005863e+00,1.6540306807e+00,6.7592434585e-02,1.3668476343e+00,1.0540937185e+00,1.0810308903e-01,...,6.3831120729e-02,1.4211839065e-02,1.7740072682e-02,2.8246941566e+00,4.6630859375e-01,8.4578499198e-02,6.3964843750e-02,0.0000000000e+00,1.7167237997e+00,6.9330163300e-02
5,5,5.2756297588e-01,-7.7654317021e-02,-2.7961030602e-01,6.8588310480e-01,1.9375696182e+00,8.8083887100e-01,-9.2319184542e-01,-9.2723226547e-01,6.6661673784e-01,...,4.0730185807e-02,1.2690781616e-02,1.4759079553e-02,6.8084154129e+00,3.7500000000e-01,5.3114086390e-02,4.1503906250e-02,0.0000000000e+00,2.1933031082e+00,4.4860601425e-02
6,10,3.7022454739e+00,-2.9119303823e-01,2.1967420578e+00,-2.3444947600e-01,1.3673638105e+00,9.9841135740e-01,1.7706941366e+00,1.6045658588e+00,5.2121698856e-01,...,7.4357867241e-02,1.7951935530e-02,1.3921394013e-02,2.1434211731e+01,4.5214843750e-01,7.7514506876e-02,7.1777343750e-02,0.0000000000e+00,3.5423245430e+00,4.0800448507e-02
7,20,-1.9383698702e-01,-1.9852678478e-01,2.0154602826e-01,2.5855624676e-01,7.7520370483e-01,8.4794059396e-02,-2.8929358721e-01,-8.1641042233e-01,4.3850939721e-02,...,9.5002755523e-02,2.2492416203e-02,2.1355332807e-02,1.6669036865e+01,4.6972656250e-01,4.7224905342e-02,4.0039062500e-02,9.7656250000e-04,3.1898307800e+00,3.0992921442e-02

In [13]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106577 entries, 0 to 106576
Columns: 519 entries, feature to zcr.6
dtypes: object(519)
memory usage: 422.0+ MB

In [23]:
features.describe(include='all')

,feature,chroma_cens,chroma_cens.1,chroma_cens.2,chroma_cens.3,chroma_cens.4,chroma_cens.5,chroma_cens.6,chroma_cens.7,chroma_cens.8,...,tonnetz.39,tonnetz.40,tonnetz.41,zcr,zcr.1,zcr.2,zcr.3,zcr.4,zcr.5,zcr.6
count,106577,106576.000000,106576.0000,106576.000000,106576.000000,106576.000000,106576.000000,106576.000000,106576.000000,106576.00000,...,106576.000000,106576.000000,106576.000000,106576.000000,106576.000000,106576.000000,106576.000000,106576.0,106576.000000,106576.000000
unique,106577,104376.000000,104381.0000,104389.000000,104394.000000,104409.000000,104378.000000,104389.000000,104383.000000,104374.00000,...,104170.000000,103962.000000,103954.000000,104379.000000,2583.000000,104218.000000,1153.000000,214.0,104320.000000,104272.000000
top,114901,2.120035,-0.1481,0.687363,1.388522,-0.779828,-1.049356,-1.352663,-1.146229,0.13384,...,0.115733,0.023668,0.022414,101.444832,0.397949,0.040447,0.024414,0.0,5.669625,0.026036
freq,1,90.000000,90.0000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.00000,...,90.000000,90.000000,90.000000,90.000000,156.000000,90.000000,1105.000000,53740.0,90.000000,90.000000

In [14]:
#echonest
echonest.columns

Index(['Unnamed: 0', 'echonest', 'echonest.1', 'echonest.2', 'echonest.3',
       'echonest.4', 'echonest.5', 'echonest.6', 'echonest.7', 'echonest.8',
       ...
       'echonest.239', 'echonest.240', 'echonest.241', 'echonest.242',
       'echonest.243', 'echonest.244', 'echonest.245', 'echonest.246',
       'echonest.247', 'echonest.248'],
      dtype='object', length=250)

In [16]:
echonest.head(8)

,Unnamed: 0,echonest,echonest.1,echonest.2,echonest.3,echonest.4,echonest.5,echonest.6,echonest.7,echonest.8,...,echonest.239,echonest.240,echonest.241,echonest.242,echonest.243,echonest.244,echonest.245,echonest.246,echonest.247,echonest.248
0,NaN,audio_features,audio_features,audio_features,audio_features,audio_features,audio_features,audio_features,audio_features,metadata,...,temporal_features,temporal_features,temporal_features,temporal_features,temporal_features,temporal_features,temporal_features,temporal_features,temporal_features,temporal_features
1,NaN,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence,album_date,...,214,215,216,217,218,219,220,221,222,223
2,track_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,0.4166752327,0.6758939853,0.6344762684,0.0106280683,0.1776465712,0.1593100648,165.9220000000,0.5766609880,NaN,...,-1.9923025370,6.8056936264,0.2330697626,0.1928800046,0.0274549890,0.0640799999,3.6769599915,3.6128799915,13.3166904449,262.9297485352
4,3,0.3744077685,0.5286430621,0.8174611317,0.0018511032,0.1058799438,0.4618181276,126.9570000000,0.2692402421,NaN,...,-1.5823311806,8.8893079758,0.2584637702,0.2209050059,0.0813684240,0.0641300008,6.0827698708,6.0186400414,16.6735477448,325.5810852051
5,5,0.0435668989,0.7455658702,0.7014699916,0.0006967990,0.3731433124,0.1245953419,100.2600000000,0.6216612236,NaN,...,-2.2883579731,11.5271091461,0.2568213642,0.2378199995,0.0601223968,0.0601399988,5.9264898300,5.8663496971,16.0138492584,356.7557373047
6,10,0.9516699648,0.6581786543,0.9245251615,0.9654270154,0.1154738842,0.0329852191,111.5620000000,0.9635898919,2008-03-11,...,-3.6629877090,21.5082283020,0.2833518982,0.2670699954,0.1257044971,0.0808200017,8.4140100479,8.3331899643,21.3170642853,483.4038085938
7,134,0.4522173071,0.5132380502,0.5604099311,0.0194426943,0.0965666940,0.5255193792,114.2900000000,0.8940722715,NaN,...,-1.4526963234,2.3563981056,0.2346863896,0.1995500028,0.1493317783,0.0644000024,11.2670698166,11.2026700974,26.4541797638,751.1477050781

In [17]:
echonest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13132 entries, 0 to 13131
Columns: 250 entries, Unnamed: 0 to echonest.248
dtypes: object(250)
memory usage: 25.0+ MB

In [24]:
echonest.describe(include='all')

,Unnamed: 0,echonest,echonest.1,echonest.2,echonest.3,echonest.4,echonest.5,echonest.6,echonest.7,echonest.8,...,echonest.239,echonest.240,echonest.241,echonest.242,echonest.243,echonest.244,echonest.245,echonest.246,echonest.247,echonest.248
count,13130,13131.000000,13131,13131,13131.00000,13131,13131,13131.00,13131.00000,2719,...,13131.000000,13131,13131.000000,13131.0000,13131.000000,13131.0000,13131.00000,13131.00000,13131.000000,13131
unique,13130,12912.000000,13131,13131,12990.00000,13131,13131,12314.00,13129.00000,444,...,13130.000000,13130,13126.000000,8929.0000,13130.000000,1478.0000,12755.00000,12991.00000,13131.000000,13131
top,32760,0.995796,0.5429413172,0.3249142017,0.97287,0.1087110744,0.5752967282,100.01,0.99999,2008,...,-1.761692,11.0926570892,0.289836,0.2322,0.020196,0.0639,2.11279,2.20122,3.544959,9.7418966293
freq,1,195.000000,1,1,38.00000,1,1,6.00,3.00000,89,...,2.000000,2,2.000000,12.0000,2.000000,109.0000,3.00000,2.00000,1.000000,1